package main

const (
	datetimeStatus        string = "enabled"
	datetimeForeground    string = "255"
	datetimeBackground    string = "232"
	usernameStatus        string = "enabled"
	usernameForeground    string = "255"
	usernameBackground    string = "235"
	hostnameStatus        string = "enabled"
	hostnameForeground    string = "255"
	hostnameBackground    string = "238"
	maximumSegments       string = "2"
	homeDirForeground     string = "255"
	homeDirBackground     string = "241"
	workingDirForeground  string = "255"
	workingDirBackground  string = "244"
	readOnlyDirForeground string = "255"
	readOnlyDirBackground string = "124"
	repositoryStatus      string = "enabled"
	repositoryForeground  string = "255"
	repositoryBackground  string = "247"
	repositoryCommittedBG string = "214"
	repositoryUntrackedBG string = "175"
	statusSymbol          string = "255"
	statusSuccess         string = "247"
	statusFailure         string = "001"
	statusMisuse          string = "003"
	statusPermission      string = "004"
	statusNotFound        string = "014"
	statusInvalidExit     string = "202"
	statusTerminated      string = "013"
	symbolRegular         string = "$"
	symbolSuperUser       string = "#"
)
